version: '3.8'
services:
  cardgame:
    build: .
    image: h3xcookie/cardgame
    ports:
      - "7777:7777"
    depends_on:
      - cardgame-pg
    environment:
      - DB_USER=user
      - DB_PASSWORD=1234
      - DB_PORT=5432
      - DB_DATABASE=cardgame
      - DB_HOST=cardgame-pg
      - SESSION_SECRET=secret

  cardgame-pg:
    build: ./database/
    image: h3xcookie/cardgame-pg
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: cardgame
